In [27]:
import numpy as np

In [25]:
class Model:
    def __init__(self):
        self.variables = []
        self.constraints = []
        self.objective = None
        self.type = None
    
    def add_variable(self, variable):
        self.variables.append(variable)
    
    def print_variables(self):
        print(" ".join([v.name for v in self.variables]))
    
    def add_constraint(self, constraint):
        self.constraints.append(constraint)
    
    def print_constraints(self):
        for c in self.constraints:
            s = ''
            for i in range(len(c.variables)):
                s += str(c.coefficients[i])+"*"+ c.variables[i].name +" + " 
            s = s[:-2]
            s += "<= " + str(c.threshold)
            print(s)
    
    def add_objective(self, coefficients, obj_type):
        self.objective = coefficients
        self.type = obj_type
    
    def print_objective(self):
        s = self.type + ":" 
        for i in range(len(self.objective)):
            s += str(self.objective[i]) + "*" + self.variables[i].name + " + "
        s = s[:-2]
        print(s)
        
    def solve(self):
        pass
    
    def _CanonicalForm(self):
        if self.type == "Min":
            self.objective = [-1*x for x in self.objective]
        
        self.slacks = []
        #create slack variable
        for i in range(len(self.constraints)):
            self.slacks.append(Variable("slack" + str(i)))
            
        c = np.array(self.objective + [0] * len(self.slacks))
        b = np.array([x.threshold for x in self.constraints])
        A = np.zeros(shape = (len(self.constraints), len(self.variables)))
        for i, c in enumerate(self.constraints):
            
        
class Variable:
    def __init__(self, name):
        self.name = name
    
class Constraint:
    '''
    Constraints are in the format:
        variables * coefficients < threshold
    '''
    def __init__(self, variables, coefficients, threshold):
        self.variables = variables
        self.coefficients = coefficients
        self.threshold = threshold        

In [26]:
m = Model()
x = []
#variables
for i in range(2):
    x.append(Variable('x'+str(i)))
    m.add_variable(x[i])

cons = Constraint([x[0], x[1]], [2, 4], 10)
m.add_constraint(cons)

m.add_objective([1, 1], 'Max')

m.print_variables()
m.print_constraints()
m.print_objective()

x0 x1
2*x0 + 4*x1 <= 10
Max:1*x0 + 1*x1 


In [29]:
np.zeros(shape = (10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#supposing that b is positive

def solve(A, b, c):
    #create slack variables
    n_constraints = A.shape[0]
    n_variables = A.shape[1]
    new_A = np.concatenate([A, np.eye(n_constraints)], axis = 1)
    
    if min(b) >= 0:
        new_b = np.array(b + [0])
        new_c = np.array(c + [0] * n_constraints)
        
        
    else:
        pass
    
    

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
A = np.array([[1, 2], [3, 4]])
np.concatenate([A, np.eye(2)], axis = 1)

array([[1., 2., 1., 0.],
       [3., 4., 0., 1.]])

In [38]:
min(np.array([1, 2, 3 ,4, 5, 6, 7]))

1